name: workout
description: An app for keeping track of your workout sessions!
repository: https://github.com/BaraShiro/WorkoutApp

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  workout_model:
    path: packages/workout_model
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  path_provider: ^2.1.1
  fpdart: ^1.1.0
  intl: ^0.18.1

dev_dependencies:
  bloc_test: ^9.1.5
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.1
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
